online_shop/chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.Room.as_view(), name='room'),
]

online_shop/customers/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordChangeView
from django.urls import path

from customers.apis import CustomerCreateApiView, UserCreateApiView, UserListApiView, UserDetailApiView, AddressListApiView, AddressDetailApiView, AddressDeleteApiView, AddressCreateApiView, UserUpdateApiView, CustomerUpdateApiView, AddressUpdateApiView, ConfirmCode
from customers.views import CustomerCreateView, AboutTemplateView, MyLoginView, CustomerDashboardTemplateView

app_name = 'customers'
urlpatterns = [
    path('customer_create_api/', CustomerCreateApiView.as_view(), name='customer_create_api'),
    path('user_create_api/', UserCreateApiView.as_view(), name='user_create_api'),
    path('sign-up/', CustomerCreateView.as_view(), name='sign-up'),
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('about/', AboutTemplateView.as_view(), name='about'),
    path('user_list_api_view/', UserListApiView.as_view(), name='user_list_api_view'),
    path('user_detail_api_view/<int:pk>', UserDetailApiView.as_view(), name='user_detail_api_view'),
    path('address_list_api_view/', AddressListApiView.as_view(), name='address_list_api_view'),
    path('address_detail_api_view/<int:pk>', AddressDetailApiView.as_view(), name='address_detail_api_view'),
    path('address_delete_api_view/<int:pk>', AddressDeleteApiView.as_view(), name='address_delete_api_view'),
    path('address_create_api_view', AddressCreateApiView.as_view(), name='address_create_api_view'),
    path('dashboard', CustomerDashboardTemplateView.as_view(), name='dashboard'),
    path('user_update_api_view/<int:pk>', UserUpdateApiView.as_view(), name='user_update_api_view'),
    path('customer_update_api_view/<int:pk>', CustomerUpdateApiView.as_view(), name='customer_update_api_view'),
    path('address_update_api_view/<int:pk>', AddressUpdateApiView.as_view(), name='address_update_api_view'),
    path('confirm_code', ConfirmCode.as_view(), name='confirm_code'),
    # path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    # path('password_change/', PasswordChangeView.as_view(), name='password_change'),
]

online_shop/online_shop/urls.py
from azbankgateways.urls import az_bank_gateways_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('bankgateways/', az_bank_gateways_urls()),
    path('payment/', include('payment.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('customers/', include('customers.urls')),
    path('orders/', include('orders.urls')),
    path('', include('products.urls')),
    path('contact/', include('contact.urls')),
    path('chat/', include('chat.urls')),
    prefix_default_language=False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

admin.site.site_header = "Web Mall Admin"
admin.site.site_title = "Web Mall"
admin.site.index_title = "Web Mall Admin"

online_shop/templates/landing/html&css/html/pages/sign-in.html
{% load i18n %}
<!--
                     {% get_current_language as LANGUAGE_CODE %}

=========================================================
* Neumorphism UI - v1.0.0
=========================================================

* Product Page: https://themesberg.com/product/ui-kits/neumorphism-ui
* Copyright 2020 Themesberg MIT LICENSE (https://www.themesberg.com/licensing#mit)

* Coded by https://themesberg.com

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

-->
<!DOCTYPE html>
<html {% if LANGUAGE_CODE == 'fa' %}lang="fa" dir="rtl" {% else %}lang="en" dir="ltr"{% endif %}>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <!-- Primary Meta Tags -->
    <title>Web Mall - {% trans 'Sign in' %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="title" content="Neumorphism UI - Sign in">
    <meta name="author" content="Themesberg">

    <link rel="canonical" href="https://themesberg.com/product/ui-kits/neumorphism-ui/"/>

    <!--  Social tags -->
    <meta name="keywords"
          content="neumorphism, neumorphism ui, neomorphism, neomorphism ui, neomorphism css, neumorphism css, neumorph, neumorphic, design system, login, form, table, tables, card, cards, navbar, modal, icons, icons, map, chat, carousel, menu, datepicker, gallery, slider, date, social, dropdown, search, tab, nav, footer, date picker, forms, tabs, time, button, select, input, timeline, cart, about us, account, log in, blog, profile, portfolio, landing page, ecommerce, shop, landing, register, app, contact, one page, sign up, signup, store, bootstrap 4, bootstrap4, dashboard, bootstrap 4 dashboard, bootstrap 4 design, bootstrap 4 system, bootstrap 4, bootstrap 4 uit kit, bootstrap 4 kit, themesberg, html kit, html css template, web template, bootstrap, bootstrap 4, css3 template, frontend, responsive bootstrap template, bootstrap ui kit, responsive ui kit">
    <meta name="description"
          content="Start developing neumorphic web applications and pages using Neumorphism UI. It features over 100 individual components and 5 example pages.">

    <!-- Schema.org markup for Google+ -->
    <meta itemprop="name" content="Neumorphism UI by Themesberg">
    <meta itemprop="description"
          content="Start developing neumorphic web applications and pages using Neumorphism UI. It features over 100 individual components and 5 example pages.">
    <meta itemprop="image"
          content="https://themesberg.s3.us-east-2.amazonaws.com/public/products/neumorphism-ui/neumorphism-thumbnail.jpg">

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="product">
    <meta name="twitter:site" content="@themesberg">
    <meta name="twitter:title" content="Neumorphism UI by Themesberg">
    <meta name="twitter:description"
          content="Start developing neumorphic web applications and pages using Neumorphism UI. It features over 100 individual components and 5 example pages.">
    <meta name="twitter:creator" content="@themesberg">
    <meta name="twitter:image"
          content="https://themesberg.s3.us-east-2.amazonaws.com/public/products/neumorphism-ui/neumorphism-thumbnail.jpg">

    <!-- Open Graph data -->
    <meta property="fb:app_id" content="214738555737136">
    <meta property="og:title" content="Neumorphism UI by Themesberg"/>
    <meta property="og:type" content="article"/>
    <meta property="og:url" content="https://demo.themesberg.com/neumorphism-ui/"/>
    <meta property="og:image"
          content="https://themesberg.s3.us-east-2.amazonaws.com/public/products/neumorphism-ui/neumorphism-thumbnail.jpg"/>
    <meta property="og:description"
          content="Start developing neumorphic web applications and pages using Neumorphism UI. It features over 100 individual components and 5 example pages."/>
    <meta property="og:site_name" content="Themesberg"/>

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="120x120"
          href="../../../../../static/landing/assets/img/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32"
          href="../../../../../static/landing/w-logo.png">
    <link rel="icon" type="image/png" sizes="16x16"
          href="../../../../../static/landing/w-logo.png">
    <link rel="manifest" href="../../../../../static/landing/assets/img/favicon/site.webmanifest">
    <link rel="mask-icon" href="../../../../../static/landing/assets/img/favicon/safari-pinned-tab.svg" color="#ffffff">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">

    <!-- Fontawesome -->
    <link type="text/css" href="../../../../../static/landing/vendor/@fortawesome/fontawesome-free/css/all.min.css"
          rel="stylesheet">

    <!-- Pixel CSS -->
    <link type="text/css" href="../../../../../static/landing/css/neumorphism.css" rel="stylesheet">

    <!-- NOTICE: You can use the _analytics.html partial to include production code specific code & trackers -->

</head>

<body>
<main class="{% if LANGUAGE_CODE == 'fa' %}text-right{% endif %}">
    <!-- Section -->
    <section class="min-vh-100 d-flex bg-primary align-items-center">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-md-8 col-lg-6 justify-content-center">
                    <div class="card bg-primary shadow-soft border-light p-4">
                        <div class="card-header text-center pb-0">
                            <h2 class="h4">{% trans 'Sign in to our platform' %}</h2>
                        </div>
                        <div class="card-body">
                            <form method="post" class="mt-4">
                                {% csrf_token %}
                                {% if form.errors %}
                                    <div class="alert alert-danger" role="alert">
                                        <b> {% trans 'Your username and password didnt match. Please try again.' %}</b>
                                    </div>
                                {% endif %}
                                <!-- Form -->
                                <div class="form-group">
                                    <label for="exampleInputIcon3">{% trans 'Phone' %}</label>
                                    <div class="input-group mb-4">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><span class="fas fa-phone"></span></span>
                                        </div>
                                        <input name="username" class="form-control" id="exampleInputIcon3"
                                               placeholder="09123456789" type="text" aria-label="phone">

                                    </div>
                                </div>
                                <!-- End of Form -->
                                <div class="form-group">
                                    <!-- Form -->
                                    <div class="form-group">
                                        <label for="exampleInputPassword6">{% trans 'Password' %}</label>
                                        <div class="input-group mb-4">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><span
                                                        class="fas fa-unlock-alt"></span></span>
                                            </div>
                                            <input name="password" class="form-control" id="exampleInputPassword6"
                                                   placeholder="Password" type="password" aria-label="Password"
                                                   required>
                                        </div>
                                    </div>
                                    <!-- End of Form -->
                                    <div class="d-block d-sm-flex justify-content-between align-items-center mb-4">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="defaultCheck5">
{#                                            <label class="form-check-label" for="defaultCheck5">#}
{#                                                Remember me#}
{#                                            </label>#}
                                        </div>
                                        <div><a href="#" class="small text-right">{% trans 'Lost password?' %}</a></div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-block btn-primary">{% trans 'Sign in' %}</button>
                            </form>
{#                            <div class="mt-3 mb-4 text-center">#}
{#                                <span class="font-weight-normal">or login with</span>#}
{#                            </div>#}
{#                            <div class="btn-wrapper my-4 text-center">#}
{#                                <button class="btn btn-primary btn-icon-only text-facebook mr-2" type="button"#}
{#                                        aria-label="facebook button" title="facebook button">#}
{#                                    <span aria-hidden="true" class="fab fa-facebook-f"></span>#}
{#                                </button>#}
{#                                <button class="btn btn-primary btn-icon-only text-twitter mr-2" type="button"#}
{#                                        aria-label="twitter button" title="twitter button">#}
{#                                    <span aria-hidden="true" class="fab fa-twitter"></span>#}
{#                                </button>#}
{#                                <button class="btn btn-primary btn-icon-only text-facebook" type="button"#}
{#                                        aria-label="github button" title="github button">#}
{#                                    <span aria-hidden="true" class="fab fa-github"></span>#}
{#                                </button>#}
{#                            </div>#}
                            <div class="d-block d-sm-flex justify-content-center align-items-center mt-4">
                                    <span class="font-weight-normal">
                                        {% trans 'Not registered?' %}
                                        <a href="{% url 'customers:sign-up' %}"
                                           class="font-weight-bold">{% trans 'Create account' %}</a>
                                    </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

<!-- Core -->
<script src="../../../../../static/landing/vendor/jquery/dist/jquery.min.js"></script>
<script src="../../../../../static/landing/vendor/popper.js/dist/umd/popper.min.js"></script>
<script src="../../../../../static/landing/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="../../../../../static/landing/vendor/headroom.js/dist/headroom.min.js"></script>

<!-- Vendor JS -->
<script src="../../../../../static/landing/vendor/onscreen/dist/on-screen.umd.min.js"></script>
<script src="../../../../../static/landing/vendor/nouislider/distribute/nouislider.min.js"></script>
<script src="../../../../../static/landing/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<script src="../../../../../static/landing/vendor/waypoints/lib/jquery.waypoints.min.js"></script>
<script src="../../../../../static/landing/vendor/jarallax/dist/jarallax.min.js"></script>
<script src="../../../../../static/landing/vendor/jquery.counterup/jquery.counterup.min.js"></script>
<script src="../../../../../static/landing/vendor/jquery-countdown/dist/jquery.countdown.min.js"></script>
<script src="../../../../../static/landing/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>
<script src="../../../../../static/landing/vendor/prismjs/prism.js"></script>

<script async defer src="https://buttons.github.io/buttons.js"></script>

<!-- Neumorphism JS -->
<script src="../../../../../static/landing/assets/js/neumorphism.js"></script>
</body>

</html>