online_shop/chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.Room.as_view(), name='room'),
]

online_shop/online_shop/urls.py
from azbankgateways.urls import az_bank_gateways_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('bankgateways/', az_bank_gateways_urls()),
    path('payment/', include('payment.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('customers/', include('customers.urls')),
    path('orders/', include('orders.urls')),
    path('', include('products.urls')),
    path('contact/', include('contact.urls')),
    path('chat/', include('chat.urls')),
    prefix_default_language=False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

admin.site.site_header = "Web Mall Admin"
admin.site.site_title = "Web Mall"
admin.site.index_title = "Web Mall Admin"

online_shop/products/urls.py
from django.urls import path

from products.views import ProductListView, ProductDetailView, CategoryDetailView
from .apis import ProductListApiView, ProductDetailApiView, CategoryProductsListApiView, CommentCreateApiView

app_name = 'products'
urlpatterns = [
    path('', ProductListView.as_view(), name='products_list'),
    path('product_detail/<int:pk>', ProductDetailView.as_view(), name='product_detail'),
    # path('products_list_api/', product_list_api, name='products_list_api'),
    path('products_list_api/', ProductListApiView.as_view(), name='products_list_api'),
    path('comment_create_api/', CommentCreateApiView.as_view(), name='comment_create_api'),
    path('products_detail_api/<int:pk>', ProductDetailApiView.as_view(), name='products_detail_api'),
    path('category_detail/<int:pk>', CategoryDetailView.as_view(), name='category_detail'),
    path('category_products_list_api/<int:category_id>', CategoryProductsListApiView.as_view(), name='category_products_list_api'),
    # path('products_tamplate/', ProductTemplateView.as_view(), name='products_template'),
]

online_shop/templates/path/to/comment_tree_structure.html
{% load i18n %}
{% load product_extras %}
<ul class="list-style-none">
    {% for sub in subs %}
        <li class="dropdown-item bg-primary">
            <div class="row ml-auto">
                <div
                        class="card-body shadow-soft text-center border border-light rounded col-12 col-md-11">
                    <div class="container-fluid">
                        <div class="row">
                            <img src="{{ sub.customer.image.url }}"
                                 alt="{{ sub.customer.first_name }}"
                                 class="col-2 mr-auto rounded-circle">
                            <div class="my-auto container-fluid col-10">
                                <div class="row">
                                    {% if not sub.customer.user.first_name and not sub.customer.user.last_name %}
                                        <h4 class="col-12 text-left">{% trans 'No Name' %} {{ sub.customer }}<span
                                                    class="fas fa-clock ml-5"> {{ sub.created }}</span></h4>
                                        <h6 class="col-12 text-left"><span class="fas fa-reply text-danger"> to
                                            {% if not parent.customer.user.first_name and not parent.customer.user.last_name %}
                                                {% trans 'No Name' %}
                                            {% else %}
                                                {{ parent.customer.user.first_name }}
                                                {{ parent.customer.user.last_name }}{% endif %}</span></h6>
                                    {% else %}
                                        <h4 class="col-12 text-left">{{ sub.customer.user.first_name }} {{ sub.customer.user.last_name }}
                                            <span class="fas fa-clock ml-5"> {{ sub.created }}</span></h4>
                                        <h6 class="col-12 text-left"><span class="fas fa-reply text-danger"> {% trans 'to' %}
                                            {% if not parent.customer.user.first_name and not parent.customer.user.last_name %}
                                                {% trans 'No Name' %}
                                            {% else %}
                                                {{ parent.customer.user.first_name }}
                                                {{ parent.customer.user.last_name }}{% endif %}</span></h6>
                                    {% endif %}
                                    <p class="mt-2 text-left col-12">{{ sub.text }}</p>
                                    <p class="mt-2 text-left col-12"><button type="button"
                                            class="fas fa-thumbs-up text-success border-0 bg-primary"> {{ sub.likes }}</button><button type="button"
                                            class="fas fa-thumbs-down text-danger mx-4 border-0 bg-primary"> {{ sub.diss_likes }}</button><button type="button"
                                            class="fas fa-reply text-secondary border-0 bg-primary"> {% trans 'Reply' %}</button></p>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                {% comment_tree_structure sub %}
            </div>
        </li>
    {% endfor %}
</ul>

online_shop/templates/path/to/tree_structure.html
{% load i18n %}
{% load product_extras %}
<ul class="list-style-none">
    {% for sub in subs %}
        <a href="{% url 'products:category_detail' pk=sub.id %}">
        <li class="dropdown-item">
           {% trans sub.name %}
{#            {% if sub.parent.count > 0 %}#}
                {% tree_structure sub %}
{#            {% endif %}#}
        </li>
        </a>
    {% endfor %}
</ul>