online_shop/chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.Room.as_view(), name='room'),
]

online_shop/online_shop/urls.py
from azbankgateways.urls import az_bank_gateways_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('bankgateways/', az_bank_gateways_urls()),
    path('payment/', include('payment.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('customers/', include('customers.urls')),
    path('orders/', include('orders.urls')),
    path('', include('products.urls')),
    path('contact/', include('contact.urls')),
    path('chat/', include('chat.urls')),
    prefix_default_language=False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

admin.site.site_header = "Web Mall Admin"
admin.site.site_title = "Web Mall"
admin.site.index_title = "Web Mall Admin"

online_shop/templates/landing/html&css/html/pages/layout/_base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html {% if LANGUAGE_CODE == 'fa' %}lang="fa" dir="rtl" {% else %}lang="en" dir="ltr"{% endif %}>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <!-- Primary Meta Tags -->
    <title>{% block title %}{% endblock %} | {% trans site_setting.site_name %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="title" content="Neumorphism UI - Pricing">
    <meta name="author" content="Themesberg">

    <link rel="canonical" href="https://themesberg.com/product/ui-kits/neumorphism-ui/"/>

    <!--  Social tags -->
    <meta name="keywords"
          content="neumorphism, neumorphism ui, neomorphism, neomorphism ui, neomorphism css, neumorphism css, neumorph, neumorphic, design system, login, form, table, tables, card, cards, navbar, modal, icons, icons, map, chat, carousel, menu, datepicker, gallery, slider, date, social, dropdown, search, tab, nav, footer, date picker, forms, tabs, time, button, select, input, timeline, cart, about us, account, log in, blog, profile, portfolio, landing page, ecommerce, shop, landing, register, app, contact, one page, sign up, signup, store, bootstrap 4, bootstrap4, dashboard, bootstrap 4 dashboard, bootstrap 4 design, bootstrap 4 system, bootstrap 4, bootstrap 4 uit kit, bootstrap 4 kit, themesberg, html kit, html css template, web template, bootstrap, bootstrap 4, css3 template, frontend, responsive bootstrap template, bootstrap ui kit, responsive ui kit">
    <meta name="description"
          content="Start developing neumorphic web applications and pages using Neumorphism UI. It features over 100 individual components and 5 example pages.">

    <!-- Schema.org markup for Google+ -->
    <meta itemprop="name" content="Neumorphism UI by Themesberg">
    <meta itemprop="description"
          content="Start developing neumorphic web applications and pages using Neumorphism UI. It features over 100 individual components and 5 example pages.">
    <meta itemprop="image"
          content="https://themesberg.s3.us-east-2.amazonaws.com/public/products/neumorphism-ui/neumorphism-thumbnail.jpg">

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="product">
    <meta name="twitter:site" content="@themesberg">
    <meta name="twitter:title" content="Neumorphism UI by Themesberg">
    <meta name="twitter:description"
          content="Start developing neumorphic web applications and pages using Neumorphism UI. It features over 100 individual components and 5 example pages.">
    <meta name="twitter:creator" content="@themesberg">
    <meta name="twitter:image"
          content="https://themesberg.s3.us-east-2.amazonaws.com/public/products/neumorphism-ui/neumorphism-thumbnail.jpg">

    <!-- Open Graph data -->
    <meta property="fb:app_id" content="214738555737136">
    <meta property="og:title" content="Neumorphism UI by Themesberg"/>
    <meta property="og:type" content="article"/>
    <meta property="og:url" content="https://demo.themesberg.com/neumorphism-ui/"/>
    <meta property="og:image"
          content="https://themesberg.s3.us-east-2.amazonaws.com/public/products/neumorphism-ui/neumorphism-thumbnail.jpg"/>
    <meta property="og:description"
          content="Start developing neumorphic web applications and pages using Neumorphism UI. It features over 100 individual components and 5 example pages."/>
    <meta property="og:site_name" content="Themesberg"/>

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="120x120" href="{{ site_setting.logo.url }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ site_setting.logo.url }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ site_setting.logo.url }}">
    <link rel="manifest" href="../../../../../static/landing/assets/img/favicon/site.webmanifest">
    <link rel="mask-icon" href="../../../../../static/landing/assets/img/favicon/safari-pinned-tab.svg" color="#ffffff">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">

    <!-- Fontawesome -->
    <link type="text/css" href="../../../../../static/landing/vendor/@fortawesome/fontawesome-free/css/all.min.css"
          rel="stylesheet">

    <!-- Pixel CSS -->
    <link type="text/css" href="../../../../../static/landing/css/neumorphism.css" rel="stylesheet">
    {% load static %}
    {#    <link rel="stylesheet" href="{% static 'layout/css/fa-font.css' %}">#}

    <link rel="stylesheet" href="{% static 'layout/css/loading.css' %}">

    <!-- NOTICE: You can use the _analytics.html partial to include production code specific code & trackers -->
    {% block extra_head %}{% endblock %}
</head>

<body>
{% load humanize %}
{% load product_extras %}
{% include 'landing/html&css/html/pages/layout/__header.html' %}
{% block content %}
{% endblock %}
{% if login %}
    <a class='bg-body rounded-circle shadow-soft' id="producthunt-badge"
       href="{% url 'chat:room' room_name=user.phone %}" target="_blank"><img
            src="{% static 'chat/supportchatlogo.png' %}" alt="online support" style="height: 100px" height="100px"></a>
{% endif %}
{#<div class="bg-dark text-white rounded shadow-soft p-1" style="position: fixed;bottom: 25px;left: 25px;z-index: 99;">#}
{#    {% get_current_language as LANGUAGE_CODE %}#}
{#    {% get_available_languages as LANGUAGES %}#}
{#    {% get_language_info_list for LANGUAGES as languages %}#}
{#    <ul class="mr-auto text-secondary">#}
{#        {% for lang in languages %}#}
{#            <li class="text-center">#}
{#                <a href="/{{ lang.code }}/" class="mx-auto" {% if lang.code == LANGUAGE_CODE %}{% endif %}>#}
{#                    {{ lang.code }}#}
{#                </a>#}
{#            </li>#}
{#        {% endfor %}#}
{#    </ul>#}
{##}
{#</div>#}
<footer class="d-flex pb-5 pt-6 pt-md-7 border-top border-light bg-primary">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <p><strong>{{ site_setting.site_name }}</strong>{{ site_setting.description }}</p>
            </div>
            <div class="col-6 col-lg-2 mb-5 mb-lg-0">
                <h5 class="fas fa-phone"><a href="tel:{{ site_setting.contact_phone }}" class="border-bottom border-dark">{{ site_setting.contact_phone }}</a></h5>
{#                <ul class="footer-links list-unstyled mt-2">#}
{#                    <li class="mb-1"><a class="p-2" target="_blank" href="https://themesberg.com/blog">Blog</a></li>#}
{#                    <li class="mb-1"><a class="p-2" target="_blank" href="https://themesberg.com/products">Products</a>#}
{#                    </li>#}
{#                    <li class="mb-1"><a class="p-2" target="_blank" href="https://themesberg.com/about">About Us</a>#}
{#                    </li>#}
{#                    <li><a class="p-2" target="_blank" href="https://themesberg.com/contact">Contact Us</a></li>#}
{#                </ul>#}
            </div>
            <div class="col-6 col-lg-2 mb-5 mb-lg-0">
                <h5>Social Medias</h5>
                                <ul class="d-flex list-unstyled mb-5 mb-lg-0">
                    <li class="mr-2">
                        <a href="{{ site_setting.telegram_link }}" target="_blank"
                           class="btn btn-icon-only btn-pill btn-primary" aria-label="telegram social link"
                           data-toggle="tooltip" data-placement="top" title="DM on telegram">
                            <span aria-hidden="true" class="fab fa-telegram"></span>
                        </a>
                    </li>
                    <li class="mr-2">
                        <a href="{{ site_setting.instagram_link }}" target="_blank"
                           class="btn btn-icon-only btn-pill btn-primary" aria-label="instagram social link"
                           data-toggle="tooltip" data-placement="top" title="Like on instagram">
                            <span aria-hidden="true" class="fab fa-instagram"></span>
                        </a>
                    </li>
                    <li class="mr-2">
                        <a href="{{ site_setting.github_link }}" target="_blank"
                           class="btn btn-icon-only btn-pill btn-primary" aria-label="github social link"
                           data-toggle="tooltip" data-placement="top" title="Open source projects">
                            <span aria-hidden="true" class="fab fa-github"></span>
                        </a>
                    </li>

                </ul>

{#                <ul class="footer-links list-unstyled mt-2">#}
{#                    <li class="mb-1"><a class="p-2"#}
{#                                        href="https://themesberg.com/docs/pixel-bootstrap/getting-started/overview/"#}
{#                                        target="_blank">Docs#}
{#                        <span class="badge badge-gray text-uppercase ml-2">v1.0</span></a>#}
{#                    </li>#}
{#                    <li class="mb-1">#}
{#                        <a class="p-2" href="https://themesberg.com/docs/pixel-bootstrap/getting-started/changelog"#}
{#                           target="_blank">Changelog</a>#}
{#                    </li>#}
{#                    <li class="mb-1">#}
{#                        <a class="p-2" target="_blank" href="https://themesberg.com/licensing">License</a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a class="p-2" target="_blank"#}
{#                           href="https://github.com/themesberg/pixel-bootstrap-ui-kit/issues">Support</a>#}
{#                    </li>#}
{#                </ul>#}
            </div>
            <div class="col-12 col-lg-4 mb-5 mb-lg-0">
                <h5><a href="mailto:{{ site_setting.contact_email }}" class="border-bottom border-dark">{{ site_setting.contact_email }}</a></h5>
                <p class="text-gray font-small mt-2">{{ site_setting.email_description }}</p>
{#                <form action="#">#}
{#                    <div class="form-row mb-2">#}
{#                        <div class="col-12">#}
{#                            <label class="h6 font-weight-normal d-none" for="exampleInputEmail3">Email address</label>#}
{#                            <input type="email" class="form-control mb-2" placeholder="example@company.com" name="email"#}
{#                                   aria-label="Subscribe form" id="exampleInputEmail3" required>#}
{#                        </div>#}
{#                        <div class="col-12">#}
{#                            <button type="submit" class="btn btn-primary btn-block" data-loading-text="Sending">#}
{#                                <span>Subscribe</span>#}
{#                            </button>#}
{#                        </div>#}
{#                    </div>#}
{#                </form>#}
{#                <p class="text-gray font-small m-0">We’ll never share your details. See our <a class="text-black"#}
{#                                                                                               href="#">Privacy#}
{#                    Policy</a></p>#}
            </div>
        </div>
        <hr class="my-5">
        <div class="row">
            <div class="col">
                <a href="#" target="_blank" class="d-flex justify-content-center">
                    <img src="{{ site_setting.logo.url }}" height="25" class="mb-3"
                         alt="Site Logo">
                </a>
                <div class="d-flex text-center justify-content-center align-items-center" role="contentinfo">
                    <p class="font-weight-normal font-small mb-0">Copyright © {{ site_setting.site_name }}
                        <span class="current-year">2022</span>. All rights reserved.</p>
                </div>
            </div>
        </div>
    </div>
</footer>
<div class="loading_modal"><!-- Place at bottom of page --></div>

<!-- Core -->
<script src="../../../../../static/landing/vendor/jquery/dist2/jquery3-6.min.js"></script>
<script src="../../../../../static/landing/vendor/popper.js/dist/umd/popper.min.js"></script>
<script src="../../../../../static/landing/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="../../../../../static/landing/vendor/headroom.js/dist/headroom.min.js"></script>

<!-- Vendor JS -->
<script src="../../../../../static/landing/vendor/onscreen/dist/on-screen.umd.min.js"></script>
<script src="../../../../../static/landing/vendor/nouislider/distribute/nouislider.min.js"></script>
<script src="../../../../../static/landing/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<script src="../../../../../static/landing/vendor/waypoints/lib/jquery.waypoints.min.js"></script>
<script src="../../../../../static/landing/vendor/jarallax/dist/jarallax.min.js"></script>
<script src="../../../../../static/landing/vendor/jquery.counterup/jquery.counterup.min.js"></script>
<script src="../../../../../static/landing/vendor/jquery-countdown/dist/jquery.countdown.min.js"></script>
<script src="../../../../../static/landing/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>
<script src="../../../../../static/landing/vendor/prismjs/prism.js"></script>

<script async defer src="https://buttons.github.io/buttons.js"></script>

<!-- Neumorphism JS -->
<script src="../../../../../static/landing/assets/js/neumorphism.js"></script>
<script>
    $body = $("body");

    $(document).on({
        ajaxStart: function () {
            $body.addClass("loading");
        },
        ajaxStop: function () {
            $body.removeClass("loading");
        }
    });

    function non_destroyer(value) {
        if (!value) {
            return '-'
        } else {
            return value
        }
    }
</script>
{% block extra_scripts %}{% endblock %}
</body>

</html>